name = "aiphotobooth"
main = "index.js"
type = "service"
compatibility_date = "2026-01-01"

# Переменные
[vars]
ENVIRONMENT = "production"
YOOKASSA_SHOP_ID = "1249956"

# R2 Бакет (правильный)
[[r2_buckets]]
binding = "BUCKET"
bucket_name = "fotoai"

# D1 База данных (правильная)
[[d1_databases]]
binding = "DB"
database_name = "foto_db"
database_id = "03828eee-b0eb-4e46-9dd1-903d26dceab4"

# KV Namespace
[[kv_namespaces]]
binding = "KV"
id = "6e3f07dbb09b45f3bb10046e502c8d9a"

# Queue
[[queues.producers]]
binding = "Queue"
queue = "aiphotobooth"